events {
}

http {
    server {
        listen 80;
        location /api/ {
            proxy_pass http://host.docker.internal:8081;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        location / {
            auth_request /auth_check;
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location = /auth_check {
            internal;
            proxy_pass http://host.docker.internal:8081/api/validate-session;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_pass_request_body off;
            proxy_set_header Content-Length 0;
        }
    }
}
