ALTER TABLE counters
ADD COLUMN type VARCHAR(20) DEFAULT 'standard' NOT NULL,
ADD COLUMN frequency BIGINT DEFAULT 0,
ADD COLUMN alert_window BIGINT DEFAULT 0,
ADD COLUMN last_performed_at TIMESTAMPTZ DEFAULT now();
