package db

import (
	"context"
	"database/sql"
	"fmt"
	"time"
)

// Counter represents a row in the `counters` table. Fields are exported
// so that callers can inspect data after fetching.
type Counter struct {
	ID              int        `json:"id"`
	UserID          int        `json:"user_id"`
	Name            string     `json:"name"`
	CreateTime      time.Time  `json:"createtime"`
	ArchiveTime     *time.Time `json:"archivetime"`
	DeleteTime      *time.Time `json:"deletetime"`
	Step            int        `json:"step"`
	Type            string     `json:"type"`
	Frequency       *int64     `json:"frequency"`
	AlertWindow     *int64     `json:"alert_window"`
	LastPerformedAt *time.Time `json:"last_performed_at"`
	PriorityScore   float64    `json:"priority_score"`
	RepeatStatus    string     `json:"repeat_status"`
}

// GetCountersCount returns the number of counters based on deletion status.
func GetCountersCount(ctx context.Context, deleted bool) (int, error) {
	if db == nil {
		return 0, fmt.Errorf("database not initialized")
	}
	var query string
	if deleted {
		query = "SELECT count(*) FROM counters WHERE deletetime IS NOT NULL"
	} else {
		query = "SELECT count(*) FROM counters WHERE deletetime IS NULL"
	}
	var count int
	err := db.QueryRow(query).Scan(&count)
	if err != nil {
		return 0, err
	}
	return count, nil
}

// GetUserIdForCounter returns the owning user ID for a given counter
// ID, provided the counter is not deleted. It returns sql.ErrNoRows
// if the counter does not exist or is deleted.
func GetUserIdForCounter(counterID int) (int, error) {
    if db == nil {
        return 0, fmt.Errorf("database not initialized")
    }
    const query = `SELECT "user" FROM counters WHERE id=$1 AND deletetime IS NULL`
    var userID int
    err := db.QueryRow(query, counterID).Scan(&userID)
    if err != nil {
        return 0, err
    }
    return userID, nil
}
// InsertCounter inserts a new counter for the supplied user ID and name.
// It returns the complete Counter record with its autogenerated ID and
// creation timestamp.
func InsertCounter(userID int, name string, step int, cType string, frequency *int64, alertWindow *int64) (*Counter, error) {
	if db == nil {
		return nil, fmt.Errorf("database not initialized")
	}
	const query = `INSERT INTO counters ("user", name, step, type, frequency, alert_window, last_performed_at) VALUES ($1, $2, $3, $4, $5, $6, '1970-01-01 00:00:00+00') RETURNING id, createtime, step, type, frequency, alert_window`
	var c Counter
	c.UserID = userID
	c.Name = name
	var createTime time.Time
	var insertedStep int
	var insertedType string
	var insertedFreq *int64
	var insertedAlert *int64
	err := db.QueryRow(query, userID, name, step, cType, frequency, alertWindow).Scan(&c.ID, &createTime, &insertedStep, &insertedType, &insertedFreq, &insertedAlert)
	if err != nil {
		return nil, err
	}
	c.CreateTime = createTime
	c.Step = insertedStep
	c.Type = insertedType
	c.Frequency = insertedFreq
	c.AlertWindow = insertedAlert
	return &c, nil
}

// GetCountersForUser retrieves all counters that the user owns or has access to via shared tags.
// The returned slice may be empty if the user has no counters.
func GetCountersForUser(userID int) ([]*Counter, error) {
	if db == nil {
		return nil, fmt.Errorf("database not initialized")
	}
	const query = `
		SELECT DISTINCT c.id, c."user", c.name, c.createtime, c.archivetime, c.step, c.deletetime, c.type, c.frequency, c.alert_window, c.last_performed_at
		FROM counters c
		LEFT JOIN counter_tags ct ON c.id = ct.counter_id
		LEFT JOIN tags t ON ct.tag_id = t.id
		LEFT JOIN tag_shares ts ON t.id = ts.tag_id
		WHERE c.deletetime IS NULL
		  AND (c."user" = $1 OR t.user_id = $1 OR ts.user_id = $1)
		ORDER BY c.id`
	rows, err := db.Query(query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	counters := make([]*Counter, 0)
	for rows.Next() {
		var c Counter
		var archiveTime, deleteTime sql.NullTime
		var lastPerformedAt sql.NullTime
		var freq, alert sql.NullInt64
		if err := rows.Scan(&c.ID, &c.UserID, &c.Name, &c.CreateTime, &archiveTime, &c.Step, &deleteTime, &c.Type, &freq, &alert, &lastPerformedAt); err != nil {
			return nil, err
		}
		if archiveTime.Valid {
			c.ArchiveTime = &archiveTime.Time
		}
		if deleteTime.Valid {
			c.DeleteTime = &deleteTime.Time
		}
		if lastPerformedAt.Valid {
			c.LastPerformedAt = &lastPerformedAt.Time
		}
		if freq.Valid {
			f := freq.Int64
			c.Frequency = &f
		}
		if alert.Valid {
			a := alert.Int64
			c.AlertWindow = &a
		}
		
		// Calculate Priority
		if c.Type == "repeating" && c.Frequency != nil && c.LastPerformedAt != nil {
			now := time.Now()
			dueDate := c.LastPerformedAt.Add(time.Duration(*c.Frequency) * time.Second)
			
			alertWindowSecs := int64(0)
			if c.AlertWindow != nil {
				alertWindowSecs = *c.AlertWindow
			}
			
			visibleDate := dueDate.Add(-time.Duration(alertWindowSecs) * time.Second)
			
			if now.After(visibleDate) {
				c.RepeatStatus = "active"
				c.PriorityScore = now.Sub(visibleDate).Seconds()
			} else {
				c.RepeatStatus = "sleeping"
				c.PriorityScore = 0
			}
		} else {
			c.RepeatStatus = "n/a"
			c.PriorityScore = 0
		}
		
		counters = append(counters, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return counters, nil
}

// UpdateCounter updates the name and step of a counter.
// It returns true if the counter was updated, false if it wasn't found or belongs to another user.
func UpdateCounter(userID int, counterID int, name string, step int, cType string, frequency *int64, alertWindow *int64) (bool, error) {
	if db == nil {
		return false, fmt.Errorf("database not initialized")
	}
	const query = `UPDATE counters SET name = $1, step = $2, type = $3, frequency = $4, alert_window = $5
	WHERE "user" = $6 AND id = $7 AND deletetime IS NULL`
	res, err := db.Exec(query, name, step, cType, frequency, alertWindow, userID, counterID)
	if err != nil {
		return false, err
	}
	rows, err := res.RowsAffected()
	if err != nil {
		return false, err
	}
	return rows > 0, nil
}

// SoftDeleteCounter marks a counter as deleted by setting its
// `deletetime` column to the current timestamp. The deletion is
// scoped to the specified `userID` to prevent one user from
// deleting another's counters. The function returns true if a row was
// updated and false if no matching counter was found.
func SoftDeleteCounter(userID int, counterID int) (bool, error) {
    if db == nil {
        return false, fmt.Errorf("database not initialized")
    }
    const query = `UPDATE counters SET deletetime = now()
    WHERE "user" = $1 AND id = $2 AND deletetime IS NULL`
    res, err := db.Exec(query, userID, counterID)
    if err != nil {
        return false, err
    }
    rows, err := res.RowsAffected()
    if err != nil {
        return false, err
    }
    return rows > 0, nil
}

// SetCounterArchiveTime sets or clears the archivetime of a counter.
// If archiveTime is nil, it clears the archive time.
func SetCounterArchiveTime(userID int, counterID int, archiveTime *time.Time) (bool, error) {
    if db == nil {
            return false, fmt.Errorf("database not initialized")
    }
    var query string
    var args []interface{}
    if archiveTime == nil {
            query = `UPDATE counters SET archivetime = NULL WHERE "user" = $1 AND id = $2 AND deletetime IS NULL`
            args = []interface{}{userID, counterID}
    } else {
            query = `UPDATE counters SET archivetime = $1 WHERE "user" = $2 AND id = $3 AND deletetime IS NULL`
            args = []interface{}{*archiveTime, userID, counterID}
    }

    res, err := db.Exec(query, args...)
    if err != nil {
            return false, err
    }
    rows, err := res.RowsAffected()
    if err != nil {
            return false, err
    }
    return rows > 0, nil
}



// GetUsersWithAccessToCounter retrieves all user IDs who have access to a counter,
// either as the owner or via shared tags.
func GetUsersWithAccessToCounter(counterID int) ([]int, error) {
	if db == nil {
		return nil, fmt.Errorf("database not initialized")
	}
	const query = `
		SELECT "user" FROM counters WHERE id = $1 AND deletetime IS NULL
		UNION
		SELECT ts.user_id FROM counter_tags ct
		JOIN tag_shares ts ON ct.tag_id = ts.tag_id
		WHERE ct.counter_id = $1
		UNION
		SELECT t.user_id FROM counter_tags ct
		JOIN tags t ON ct.tag_id = t.id
		WHERE ct.counter_id = $1`
	rows, err := db.Query(query, counterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var users []int
	for rows.Next() {
		var uid int
		if err := rows.Scan(&uid); err != nil {
			return nil, err
		}
		users = append(users, uid)
	}
	return users, nil
}
// A user can edit a counter if they own it, or if it is tagged with a tag they have edit access to.
func CanUserEditCounter(userID int, counterID int) (bool, error) {
	if db == nil {
		return false, fmt.Errorf("database not initialized")
	}
	const query = `
		SELECT 1 FROM counters c
		LEFT JOIN counter_tags ct ON c.id = ct.counter_id
		LEFT JOIN tag_shares ts ON ct.tag_id = ts.tag_id
		WHERE c.id = $1 AND c.deletetime IS NULL
		  AND (c."user" = $2 OR (ts.user_id = $2 AND ts.access_level = 2))
		LIMIT 1`
	var exists int
	err := db.QueryRow(query, counterID, userID).Scan(&exists)
	if err != nil {
		if err == sql.ErrNoRows {
			return false, nil
		}
		return false, err
	}
	return true, nil
}
func GetCountersByTag(userID int, tagID int) ([]*Counter, error) {
	if db == nil {
		return nil, fmt.Errorf("database not initialized")
	}
	const query = `
		SELECT DISTINCT c.id, c."user", c.name, c.createtime, c.archivetime, c.step, c.deletetime
		FROM counters c
		JOIN counter_tags ct ON c.id = ct.counter_id
		JOIN tags t ON ct.tag_id = t.id
		LEFT JOIN tag_shares ts ON t.id = ts.tag_id
		WHERE c.deletetime IS NULL
		  AND t.id = $1
		  AND (t.user_id = $2 OR ts.user_id = $2)
		ORDER BY c.id`
	rows, err := db.Query(query, tagID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	counters := make([]*Counter, 0)
	for rows.Next() {
		var c Counter
		var archiveTime sql.NullTime
		var deleteTime sql.NullTime
		var step int
		if err := rows.Scan(&c.ID, &c.UserID, &c.Name, &c.CreateTime, &archiveTime, &step, &deleteTime); err != nil {
			return nil, err
		}
		if archiveTime.Valid {
			c.ArchiveTime = &archiveTime.Time
		}
		if deleteTime.Valid {
			c.DeleteTime = &deleteTime.Time
		}
		c.Step = step
		counters = append(counters, &c)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return counters, nil
}


