package db

import (
    "database/sql"
    "fmt"
    "time"
)

// Counter represents a row in the `counters` table. Fields are exported
// so that callers can inspect data after fetching.
type Counter struct {
    ID        int            `json:"id"`
    UserID    int            `json:"user_id"`
    Name      string         `json:"name"`
    CreateTime time.Time     `json:"createtime"`
    DeleteTime sql.NullTime  `json:"deletetime"`
    Step      int            `json:"step"`
}

// GetUserIdForCounter returns the owning user ID for a given counter
// ID, provided the counter is not deleted. It returns sql.ErrNoRows
// if the counter does not exist or is deleted.
func GetUserIdForCounter(counterID int) (int, error) {
    if db == nil {
        return 0, fmt.Errorf("database not initialized")
    }
    const query = `SELECT "user" FROM counters WHERE id=$1 AND deletetime IS NULL`
    var userID int
    err := db.QueryRow(query, counterID).Scan(&userID)
    if err != nil {
        return 0, err
    }
    return userID, nil
}
// InsertCounter inserts a new counter for the supplied user ID and name.
// It returns the complete Counter record with its autogenerated ID and
// creation timestamp.
func InsertCounter(userID int, name string) (*Counter, error) {
    if db == nil {
        return nil, fmt.Errorf("database not initialized")
    }
    // Insert the new counter. The "step" column defaults to 1 in the
    // database, so we don't need to provide a value. We return the id,
    // createtime and step for the inserted row.
    const query = `INSERT INTO counters ("user", name) VALUES ($1, $2) RETURNING id, createtime, step`
    var c Counter
    c.UserID = userID
    c.Name = name
    var createTime time.Time
    var step int
    err := db.QueryRow(query, userID, name).Scan(&c.ID, &createTime, &step)
    if err != nil {
        return nil, err
    }
    c.CreateTime = createTime
    c.Step = step
    return &c, nil
}

// GetCountersForUser retrieves all counters belonging to the given user ID.
// The returned slice may be empty if the user has no counters.
func GetCountersForUser(userID int) ([]*Counter, error) {
    if db == nil {
        return nil, fmt.Errorf("database not initialized")
    }
    const query = `SELECT id, "user", name, createtime, step, deletetime FROM counters WHERE "user"=$1 ORDER BY id`
    rows, err := db.Query(query, userID)
    if err != nil {
        return nil, err
    }
    defer rows.Close()

    var counters []*Counter
    for rows.Next() {
        var c Counter
        var deleteTime sql.NullTime
        var step int
        if err := rows.Scan(&c.ID, &c.UserID, &c.Name, &c.CreateTime, &step, &deleteTime); err != nil {
            return nil, err
        }
        c.DeleteTime = deleteTime
        c.Step = step
        counters = append(counters, &c)
    }
    if err := rows.Err(); err != nil {
        return nil, err
    }
    return counters, nil
}

// SoftDeleteCounter marks a counter as deleted by setting its
// `deletetime` column to the current timestamp. The deletion is
// scoped to the specified `userID` to prevent one user from
// deleting another's counters. The function returns true if a row was
// updated and false if no matching counter was found.
func SoftDeleteCounter(userID int, counterID int) (bool, error) {
    if db == nil {
        return false, fmt.Errorf("database not initialized")
    }
    const query = `UPDATE counters SET deletetime = now()
    WHERE "user" = $1 AND id = $2 AND deletetime IS NULL`
    res, err := db.Exec(query, userID, counterID)
    if err != nil {
        return false, err
    }
    rows, err := res.RowsAffected()
    if err != nil {
        return false, err
    }
    return rows > 0, nil
}

