package db

import (
    "database/sql"
    "fmt"
    "time"
)

// Counter represents a row in the `counters` table. Fields are exported
// so that callers can inspect data after fetching.
type Counter struct {
    ID        int            `json:"id"`
    UserID    int            `json:"user_id"`
    Name      string         `json:"name"`
    CreateTime time.Time     `json:"createtime"`
    DeleteTime sql.NullTime  `json:"deletetime"`
}

// InsertCounter inserts a new counter for the supplied user ID and name.
// It returns the complete Counter record with its autogenerated ID and
// creation timestamp.
func InsertCounter(userID int, name string) (*Counter, error) {
    if db == nil {
        return nil, fmt.Errorf("database not initialized")
    }
    const query = `INSERT INTO counters ("user", name) VALUES ($1, $2) RETURNING id, createtime`
    var c Counter
    c.UserID = userID
    c.Name = name
    var createTime time.Time
    err := db.QueryRow(query, userID, name).Scan(&c.ID, &createTime)
    if err != nil {
        return nil, err
    }
    c.CreateTime = createTime
    return &c, nil
}

// GetCountersForUser retrieves all counters belonging to the given user ID.
// The returned slice may be empty if the user has no counters.
func GetCountersForUser(userID int) ([]*Counter, error) {
    if db == nil {
        return nil, fmt.Errorf("database not initialized")
    }
    const query = `SELECT id, "user", name, createtime, deletetime FROM counters WHERE "user"=$1 ORDER BY id`
    rows, err := db.Query(query, userID)
    if err != nil {
        return nil, err
    }
    defer rows.Close()

    var counters []*Counter
    for rows.Next() {
        var c Counter
        var deleteTime sql.NullTime
        if err := rows.Scan(&c.ID, &c.UserID, &c.Name, &c.CreateTime, &deleteTime); err != nil {
            return nil, err
        }
        c.DeleteTime = deleteTime
        counters = append(counters, &c)
    }
    if err := rows.Err(); err != nil {
        return nil, err
    }
    return counters, nil
}
